module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-light": "rgb(var(--color-primary-light) / <alpha-value>)",
        "primary-dark": "rgb(var(--color-primary-dark) / <alpha-value>)",
        accent: {
          DEFAULT: "rgb(var(--color-accent) / <alpha-value>)",
          light: "rgb(var(--color-accent-light) / <alpha-value>)",
          dark: "rgb(var(--color-accent-dark) / <alpha-value>)",
        },
        danger: {
          DEFAULT: "rgb(var(--color-danger) / <alpha-value>)",
          light: "rgb(var(--color-danger-light) / <alpha-value>)",
          dark: "rgb(var(--color-danger-dark) / <alpha-value>)",
        },
        neutral: "rgb(var(--color-neutral) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        main: "rgb(var(--color-text) / <alpha-value>)",
        
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#a3caf9",
        "secondary-container": "#a9cfff",
        "on-background": "#191c1e",
        "tertiary-container": "#a95500",
        "surface-tint": "#0f5db4",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#315882",
        "tertiary": "#854100",
        "on-error-container": "#93000a",
        "outline-variant": "#c2c6d4",
        "surface-bright": "#f7f9fb",
        "on-tertiary-container": "#ffeadf",
        "on-surface-variant": "#424752",
        "on-surface": "#191c1e",
        "inverse-primary": "#a9c7ff",
        "on-primary-fixed-variant": "#00468c",
        "primary-fixed": "#d6e3ff",
        "on-secondary-fixed": "#001d36",
        "tertiary-fixed": "#ffdcc6",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "background": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#301400",
        "primary-container": "#286bc2",
        "outline": "#727783",
        "primary-fixed-dim": "#a9c7ff",
        "on-primary-fixed": "#001b3d",
        "on-primary": "#ffffff",
        "primary": "#0052a3",
        "on-secondary-fixed-variant": "#1f4971",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#713700",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed-dim": "#ffb784",
        "secondary": "#3a618b",
        "on-primary-container": "#e8eeff",
        "surface-container-high": "#e6e8ea",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed": "#d1e4ff"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        "headline": ["Manrope", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Be Vietnam Pro", "sans-serif"],
        "be-vietnam": ["Be Vietnam Pro", "sans-serif"],
      },
      borderRadius: {
        'sm': '2px',
        'md': '4px',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '16px',
        'full': '9999px',
        'DEFAULT': '0.25rem',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
      },
    },
  },
  plugins: [],
}